### ISSUE TITLE
ch1 substream not presenting codec parameters, fails in ffmpeg and others. vbuffer related?

### ISSUE THREAD

**Issue by wltechblog** [themactep/thingino-firmware#505]
Discussing this issue on Discord but tracking it here.

substream channel isn't functioning properly in most software (mpv and go2rtc seem to work).

```[rtsp @ 0x152004080] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' (1000000) and 'probesize' (1000000) options
Input #0, rtsp, from 'rtsp://thingino:thingino@192.168.82.246:554/ch1':
  Metadata:
    title           : thingino prudynt
    comment         : stream1
  Duration: N/A, start: -0.000250, bitrate: N/A
  Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
  Stream #0:1: Audio: opus, 48000 Hz, mono, fltp```

disabling vbuffer seems to be a successful workaroung.

Note from @gtxaspec 
```it's trying to create another rtsp server...hmm
[ERROR:RTSP.cpp]: Failed to create RTSP server: IPv6 bind() error (port number: 554): Address in use
for the sub stream,when it should reuse the existing one
```

workaround to disable vbuffer:
```chmod -x /etc/init.d/S96vbuffer
reboot```

**Comment by dwebfr2** [comment]
after workaround with disabling vbuffer and reboot
```
chmod -x /etc/init.d/S96vbuffer
reboot
```
substream ch1 works now in VLC, before it didnt work

**Comment by themactep** [comment]
Yes, that is prudynt peculiarity when one client (vbuffer) wants a stream without audio. That breaks things for other clients. Will need a fix.

**Comment by mattfox27** [comment]
did this get fixed?  Having issues on latest version and ffmpeg and frigate

**Comment by gtxaspec** [comment]
try the latest builds, should be fixed.

**Comment by mattfox27** [comment]
wierd im still having issues with streamer not working on latest build maybe bad hardware?

**Comment by gtxaspec** [comment]
streamer not working, at all?

**Comment by mattfox27** [comment]
No it looks like it's working but I can't pull it up in vlc

**Comment by mattfox27** [comment]
So it works for about a minute and then crashes, using latest build...I think it's hardware, I have another wyze v3 same exact setup and it works flawlessly

**Comment by themactep** [comment]
@wltechblog this is not relevant anymore, right? feel free to close.

**Comment by themactep** [comment]
Closing as stale — no reply from the original poster. This should be fixed in later builds. Reopen if still observable on the latest code.
