### ISSUE TITLE
OnVIF never sends a close connection - Home Assistant Breaks

### ISSUE THREAD

**Issue by Semag** [themactep/thingino-firmware#735]
Hey all-

The latest update to Home Assistant Broke Connections to Thingino. After doing some troubleshooting, it was found that Thingino doesn't send a Connection: Close.  See here:

_"The problem is the camera drops the connection after each post request without sending the Connection: close header so when the next request is attempted the connection has already been lost. We have a decorator for cameras that do this that needs to be applied in one more place. I am working on a patch.

It would be nice if someone reported the issue to Thingino so they can either support HTTP/1.1 keepalive or send Connection: close when the camera is going to drop the connection so the client doesn't have to guess what to do."_

https://github.com/home-assistant/core/issues/150735#issuecomment-3208084737

**Comment by themactep** [comment]
@roleoroleo can you please take a look at that? Thank you.

**Comment by roleoroleo** [comment]
I remember a similar old issue.
But I'm no able to find it now.

EDIT

1 - HA sends a GetCapabilities and the CAM replies
2 - HA sends a GetNetworkInterfaces but the CAM doesn't reply

Captured inside the cam.
It's not clear why, onvif_simple_server doesn't receive the packet from httpd: there are no logs.

<img width="1476" height="428" alt="Image" src="https://github.com/user-attachments/assets/96b6a0a6-ee8c-4710-95c2-a2c7fe507c58" />

I don't understand... maybe the client doesn't send the FIN flag?

**Comment by themactep** [comment]
@roleoroleo please look at my fork https://github.com/themactep/thingino-onvif.
onvif server does not respond because it crashes a few times on the way to the response due to memory corruption. i fixed what i found but also refactored a lot of stuff while doing that, so it won't be easy to isolate changes for a pr. [here](https://github.com/themactep/thingino-onvif/commit/c4d90ef9fbfd959fdc25486e3842d2f062be3e84) is the breakpoint cleaning part, so you can get an idea what a jorney it was. please see what you can cherry-pick back to your repo.

**Comment by roleoroleo** [comment]
Ok, I'll check it this weekend.
Thank you.

EDIT

I ported a lot of changes from your repo but I didn't fix this issue (at the moment).
I'll try again.

**Comment by roleoroleo** [comment]
I tried again following your commits (https://github.com/themactep/thingino-onvif/commit/c4d90ef9fbfd959fdc25486e3842d2f062be3e84), with no luck.
- I removed all log features.
- I used static buffer for conf_file var.
- I used static buffer for input var.

Nothing changes: when I start the wizard with HA 2025.8.2, it doesn't work.
The behavior is the same posted above (wireshark dump). The cam replies to the GetCapabilities request and doesn't reply to the GetNetworkInterfaces request.
The packet arrives to the network interface, but http doesn't start device_service CGI.
The http daemon doesn't write log lines about the second request.

I don't know what I could check.

**Comment by themactep** [comment]
I will try to restore debugging breakpoints onto your latest version and reproduce the error locally. Did you intercept the request that does not get a reply? The raw xml payload.

**Comment by roleoroleo** [comment]
Here it is.
The 1st is the GetCapabilities request, followed by the response.
Then the GetNetworkInterfaces request, without response.
Saved from a tcpdump capture executed on the cam.
The client is ha.

[Test.zip](https://github.com/user-attachments/files/22473840/Test.zip)

**Comment by themactep** [comment]
I compiled an x86-64 binary and ran in a Docker container with lighttpd. Then I added the "camera" using ONVIF integration in Home Assistant. Works like a charm.

<img width="548" height="471" alt="Image" src="https://github.com/user-attachments/assets/231f6b3e-c0e1-4942-b33c-7942682b4ac7" />

Here's the log of message exchange around `GetNetworkInterfaces`.

```
2025-09-22 19:50:15.269 DEBUG (MainThread) [onvif.zeep_aiohttp] HTTP Post to http://192.168.88.20:8000/onvif/device_service:
b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<soap-env:Envelope xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wsa="http://www.w3.org/2005/08/addressing"><soap-env:Header><wsa:Action>http://www.onvif.org/ver10/device/wsdl/GetNetworkInterfaces</wsa:Action><wsa:MessageID>urn:uuid:f2d251aa-4430-478b-8fae-7e1364d4cf37</wsa:MessageID><wsa:To>http://192.168.88.20:8000/onvif/device_service</wsa:To><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken><wsse:Username></wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">P0AGYsDbo0oUn0nAI+pKbN9fgSc=</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">Tch7e6MszoZ5+dNe9cM/iw==</wsse:Nonce><wsu:Created xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2025-09-22T23:50:15+00:00</wsu:Created></wsse:UsernameToken></wsse:Security></soap-env:Header><soap-env:Body><ns0:GetNetworkInterfaces xmlns:ns0="http://www.onvif.org/ver10/device/wsdl"/></soap-env:Body></soap-env:Envelope>'

2025-09-22 19:50:15.273 DEBUG (MainThread) [onvif.zeep_aiohttp] HTTP Response from http://192.168.88.20:8000/onvif/device_service (status: 200):
b'<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema"><SOAP-ENV:Body><tds:GetNetworkInterfacesResponse><tds:NetworkInterfaces token="NetworkInterfaceToken"><tt:Enabled>true</tt:Enabled><tt:Info><tt:Name>enp173s0</tt:Name><tt:HwAddress>b0:41:6f:17:83:d2</tt:HwAddress><tt:MTU>1500</tt:MTU></tt:Info><tt:IPv4><tt:Enabled>true</tt:Enabled><tt:Config><tt:Manual><tt:Address>192.168.88.20</tt:Address><tt:PrefixLength>24</tt:PrefixLength></tt:Manual><tt:DHCP>false</tt:DHCP></tt:Config></tt:IPv4><tt:IPv6><tt:Enabled>false</tt:Enabled></tt:IPv6></tds:NetworkInterfaces></tds:GetNetworkInterfacesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>'
```

I'll try to compile a set up for a real camera tomorrow to see if it is something specific to MIPS/musl.

**Comment by themactep** [comment]
@roleoroleo, here's [the commit](https://github.com/themactep/thingino-onvif/commit/c394a599b1926c31f07ec023b5211212c76f60ba). fast-forward against your repo. the docker container and scripts for testing.

**Comment by roleoroleo** [comment]
I'm sorry, but unfortunately I didn't fix the problem.
Even using your Docker container didn't work.
It's probably my fault, but I don't know what it is.
I solved the problem by updating HA to a later version. After updating, onvif_simple_server works with and without your changes.
Thanks anyway.

**Comment by themactep** [comment]
should be fixed in the next release. https://github.com/themactep/thingino-onvif/commit/2a27e1238766162d831325177b88b8386ff58e70
please update tomorrow, test, and report back.

**Comment by roleoroleo** [comment]
I can confirm that this patch works with my cam and HA 2025.8.2
Thanks.
